name: CI # 工作流的名称为 CI

on:
  push: # 当有代码推送时触发
    branches: # 仅触发以下分支的推送
      - main

  pull_request: # 当有 Pull Request 时触发
    branches: # 仅触发以下分支的 Pull Request
      - main

jobs:
  lint: # lint 任务
    runs-on: ubuntu-latest # 在 Ubuntu 最新版上运行

    steps:
      - uses: actions/checkout@v3 # 检出代码

      - name: Install pnpm # 安装 pnpm
        uses: pnpm/action-setup@v2

      - name: Set node # 设置 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: lts/* # 使用最新的 LTS Node.js 版本

      - name: Setup # 安装依赖
        run: npm i -g @antfu/ni

      - name: Install # 安装项目依赖
        run: nci

      - name: Lint # 执行代码 lint
        run: nr lint

  typecheck: # typecheck 任务，与 lint 类似
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Typecheck # 执行类型检查
        run: nr typecheck

  test: # test 任务
    runs-on: ${{ matrix.os }} # 在不同的操作系统上运行

    strategy: # 设置测试矩阵
      matrix:
        node: [lts/*] # 测试不同的 Node.js 版本
        os: [ubuntu-latest, windows-latest, macos-latest] # 在不同的操作系统上测试
      fail-fast: false # 允许失败任务继续执行

    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build # 执行构建
        run: nr build

      - name: Test # 执行测试
        run: nr test
